<?php

 /*               DO NOT EDIT THIS FILE

  Edit the file in the MyComponent config directory
  and run ExportObjects

 */



$packageNameLower = 'classextender'; /* No spaces, no dashes */

$components = array(
    /* These are used to define the package and set values for placeholders */
    'packageName' => 'ClassExtender',  /* No spaces, no dashes */
    'packageNameLower' => $packageNameLower,
    'packageDescription' => 'ClassExtender project for MyComponent extra',
    'version' => '2.3.3',
    'release' => 'pl',
    'author' => 'Bob Ray',
    'email' => '<https://bobsguides.com>',
    'authorUrl' => 'https://bobsguides.com',
    'authorSiteName' => "Bob's Guides",
    'packageDocumentationUrl' => 'https://bobsguides.com/classextender-tutorial.html',
    'copyright' => '2012-2023',

    /* no need to edit this except to change format */
    'createdon' => strftime('%m-%d-%Y'),

    'gitHubUsername' => 'BobRay',
    'gitHubRepository' => 'ClassExtender',

    /* two-letter code of your primary language */
    'primaryLanguage' => 'en',

    /* Set directory and file permissions for project directories */
    'dirPermission' => 0755,  /* No quotes!! */
    'filePermission' => 0644, /* No quotes!! */

    /* Define source and target directories */

    /* path to MyComponent source files */
    'mycomponentRoot' => $this->modx->getOption('mc.root', null,
        MODX_CORE_PATH . 'components/mycomponent/'),

    /* path to new project root */
    'targetRoot' => MODX_ASSETS_PATH . 'mycomponents/' . $packageNameLower . '/',


    /* *********************** NEW SYSTEM SETTINGS ************************ */

    /* If your extra needs new System Settings, set their field values here.
     * You can also create or edit them in the Manager (System -> System Settings),
     * and export them with exportObjects. If you do that, be sure to set
     * their namespace to the lowercase package name of your extra */

    'newSystemSettings' => array(
        'ce_autoload_directories' => array(
            'key' => 'ce_autoload_directories',
            'name' => 'Autoload directories',
            'description' => 'comma-separated list of directories containing class files; default: extendeduser,extendedresource',
            'namespace' => 'classextender',
            'xtype' => 'textfield',
            'value' => '',
            'area' => 'classextender'
        ),
    ),

    /* ************************ NEW SYSTEM EVENTS ************************* */

    /* Array of your new System Events (not default
     * MODX System Events). Listed here, so they can be created during
     * install and removed during uninstall.
     *
     * Warning: Do *not* list regular MODX System Events here !!! */

    'newSystemEvents' => array(
    ),

    /* ************************ NAMESPACE(S) ************************* */
    /* (optional) Typically, there's only one namespace which is set
     * to the $packageNameLower value. Paths should end in a slash
    */

    'namespaces' => array(
        'classextender' => array(
            'name' => 'classextender',
            'path' => '{core_path}components/classextender/',
            'assets_path' => '{assets_path}components/classextender/',
        ),

    ),

    /* ************************ CONTEXT(S) ************************* */
    /* (optional) List any contexts other than the 'web' context here
    */

    'contexts' => array(
    ),

    /* *********************** CONTEXT SETTINGS ************************ */

    /* If your extra needs Context Settings, set their field values here.
     * You can also create or edit them in the Manager (Edit Context -> Context Settings),
     * and export them with exportObjects. If you do that, be sure to set
     * their namespace to the lowercase package name of your extra.
     * The context_key should be the name of an actual context.
     * */

    'contextSettings' => array(
    ),

    /* ************************* CATEGORIES *************************** */
    /* (optional) List of categories. This is only necessary if you
     * need to add categories other than the one named for packageName
     * or want to nest categories.
    */

    'categories' => array(
        'ClassExtender' => array(
            'category' => 'ClassExtender',
            'parent' => '',  /* top level category */
        ),
    ),

    /* *************************** MENUS ****************************** */

    /* If your extra needs Menus, you can create them here
     * or create them in the Manager, and export them with exportObjects.
     * Be sure to set their namespace to the lowercase package name
     * of your extra.
     *
     * Every menu should have exactly one action */

    'menus' => array(
    ),

    /* ************************* ELEMENTS **************************** */

    /* Array containing elements for your extra. 'category' is required
       for each element, all other fields are optional.
       Property Sets (if any) must come first!

       The standard file names are in this form:
           SnippetName.snippet.php
           PluginName.plugin.php
           ChunkName.chunk.html
           TemplateName.template.html

       If your file names are not standard, add this field:
          'filename' => 'actualFileName',
    */


    'elements' => array(

        'propertySets' => array(
        ),

        'snippets' => array(
            'ClassExtender' => array(
                'category' => 'ClassExtender',
                'description' => 'Extend a MODX class',
            ),
            'GetExtUsers' => array(
                'category' => 'ClassExtender',
                'description' => 'Show user information',
            ),
            'GetExtResources' => array(
                'category'    => 'ClassExtender',
                'description' => 'Show resource information',
            ),

            'SetUserPlaceholders' => array(
                'category'    => 'ClassExtender',
                'description' => 'Set placeholders for extra user fields',
            ),
            'SetResourcePlaceholders' => array(
                'category'    => 'ClassExtender',
                'description' => 'Set placeholders for extra resource fields',
            ),
            'ExtUserUpdateProfile' => array(
                'category'    => 'ClassExtender',
                'description' => 'Set placeholders for and update extended user data',
            ),
            'ExtUserRegisterPosthook' => array(
                'category'    => 'ClassExtender',
                'description' => 'Update extended user data on registration',
            ),

            'UserSearchForm' => array(
                'category'    => 'ClassExtender',
                'description' => 'Show users selected by category',
            ),
            'RequireLogin' => array(
                'category' => 'ClassExtender',
                'description' => 'Show Login form to not-logged-in users',
            ),
            'CreateSchema' => array(
                'category' => 'ClassExtender',
                'description' => 'Create Schema from existing DB table',
            ),

        ),
        'plugins' => array(
            'ExtraUserFields' => array(
                'category'    => 'ClassExtender',
                'description' => 'Add and process extra fields in Create/Edit User form',
                'disabled' => true,
                'events' => array(
                    'OnUserFormRender' => array(
                        'group'       => 'plugins',
                        'propertySet' => '',
                    ),
                    'OnUserFormPreRender' => array(
                        'group'       => 'plugins',
                        'propertySet' => '',
                    ),
                    'OnUserFormSave' => array(
                        'group'       => 'plugins',
                        'propertySet' => '',
                    ),
                    'OnUserRemove' => array(
                        'group'       => 'plugins',
                        'propertySet' => '',
                    ),
                ),
            ),
            'ExtraResourceFields' => array(
                'category'    => 'ClassExtender',
                'description' => 'Add and process extra fields in Create/Edit Resource form',
                'disabled' => true,
                'events' => array(
                    'OnDocFormRender'    => array(
                        'group'       => 'plugins',
                        'propertySet' => '',
                    ),
                    'OnDocFormPreRender' => array(
                        'group'       => 'plugins',
                        'propertySet' => '',
                    ),
                    'OnDocFormSave'      => array(
                        'group'       => 'plugins',
                        'propertySet' => '',
                    ),
                    'OnEmptyTrash' => array(
                        'group'       => 'plugins',
                        'propertySet' => '',
                    ),
                ),
            ),
        ),
        'chunks' => array(
            'ExtUserSchema' => array(
                'category' => 'ClassExtender',
                'name'     => 'ExtUserSchema',
                'filename' => 'extuserschema.chunk.xml'
            ),
            'ExtResourceSchema' => array(
                'category' => 'ClassExtender',
                'name'     => 'ExtResourceSchema',
                'filename' => 'extresourceschema.chunk.xml'

            ),
            'ClassExtenderForm' => array(
                'category' => 'ClassExtender',
                'name'     => 'ClassExtenderForm',
                'filename' => 'classextenderform.chunk.html',
            ),

            'ExtraUserFields' => array(
                'category' => 'ClassExtender',
                'name' => 'ExtraUserFields',
                'filename' => 'extrauserfields.chunk.html',
            ),
            'ExtraResourceFields' => array(
                'category' => 'ClassExtender',
                'name'     => 'ExtraResourceFields',
                'filename' => 'extraresourcefields.chunk.html',
            ),
            'ExtUserOuterTpl' => array(
                'category' => 'ClassExtender',
                'name' => 'ExtUserOuterTpl',
                'filename' => 'extuseroutertpl.chunk.html',
            ),
            'ExtUserInnerTpl' => array(
                'category' => 'ClassExtender',
                'name'     => 'ExtUserInnerTpl',
                'filename' => 'extuserinnertpl.chunk.html',
            ),
            'ExtUserRowTpl' => array(
                'category' => 'ClassExtender',
                'name'     => 'ExtUserRowTpl',
                'filename' => 'extuserrowtpl.chunk.html',
            ),
            'ExtResourceOuterTpl' => array(
                'category' => 'ClassExtender',
                'name'     => 'ExtResourceOuterTpl',
                'filename' => 'extresourceoutertpl.chunk.html',
            ),
            'ExtResourceInnerTpl' => array(
                'category' => 'ClassExtender',
                'name'     => 'ExtResourceInnerTpl',
                'filename' => 'extresourceinnertpl.chunk.html',
            ),
            'ExtResourceRowTpl'   => array(
                'category' => 'ClassExtender',
                'name'     => 'ExtResourceRowTpl',
                'filename' => 'extresourcerowtpl.chunk.html',
            ),
            
            'ExtUserSearchFormTpl' => array(
                'category' => 'ClassExtender',
                'name' => 'ExtUserSearchFormTpl',
                'filename' => 'extusersearchformtpl.chunk.html',
            ),

            'ExtUserRegisterFormTpl' => array(
                'category' => 'ClassExtender',
                'name' => 'ExtUserRegisterFormTpl',
                'filename' => 'extuserregisterformtpl.chunk.html',
            ),
            'ExtUpdateProfileLoggedIn' => array(
                'category' => 'ClassExtender',
                'name' => 'ExtUpdateProfileLoggedIn',
                'filename' => 'extupdateprofileloggedin.chunk.html'
            ),
            'ExtUpdateProfileNotLoggedIn' => array(
                'category' => 'ClassExtender',
                'name' => 'ExtUpdateProfileNotLoggedIn',
                'filename' => 'extupdateprofilenotloggedin.chunk.html'
            ),
            'CreateSchemaForm' => array(
                'category' => 'ClassExtender',
                'name' => 'CreateSchemaForm',
                'filename' => 'createschemaform.chunk.html'
            ),


        ),
        'templates' => array(
        ),
        'templateVars' => array(),
    ),
    /* (optional) will make all element objects static - 'static' field above will be ignored */
    'allStatic' => false,


    /* ************************* RESOURCES ****************************
     Important: This list only affects Bootstrap. There is another
     list of resources below that controls ExportObjects.
     * ************************************************************** */
    /* Array of Resource pagetitles for your Extra; All other fields optional.
       You can set any resource field here */
    'resources' => array(
        'ClassExtender' => array(
            'pagetitle' => 'ClassExtender',
            'alias'     => 'class-extender',
            'template'  => 'default',
            'richtext'  => false,
            'published' => false,
        ),
        'Examples' => array(
            'pagetitle' => 'Examples',
            'alias' => 'examples',
            'template' => 'default',
            'parent' => 'ClassExtender',
            'richtext' => false,
            'published' => false,
        ),
        'ClassExtender Register PostHook' => array(
            'pagetitle' => 'ClassExtender Register PostHook',
            'alias' => 'classextender-register-posthook',
            'template' => 'default',
            'parent' => 'Examples',
            'richtext' => false,
            'published' => false,
        ),

        'ClassExtender Update Profile' => array(
            'pagetitle' => 'ClassExtender Update Profile',
            'alias' => 'class-extender-update-profile',
            'template' => 'default',
            'parent' => 'Examples',
            'richtext' => false,
            'published' => false,
        ),
        'ClassExtender GetExtUsers' => array(
            'pagetitle' => 'ClassExtender GetExtUsers',
            'alias' => 'class-extender-getextusers',
            'template' => 'default',
            'parent' => 'Examples',
            'richtext' => false,
            'published' => false,
        ),

        'ClassExtender GetExtResources' => array(
            'pagetitle' => 'ClassExtender GetExtResources',
            'alias' => 'class-extender-getextresources',
            'template' => 'default',
            'parent' => 'Examples',
            'richtext' => false,
            'published' => false,
        ),


        'ClassExtender Set Resource Placeholders' => array(
            'pagetitle' => 'ClassExtender Set Resource Placeholders',
            'alias' => 'class-extender-set-resource-placeholders',
            'template' => 'default',
            'parent' => 'Examples',
            'richtext' => false,
            'published' => false,
        ),

        'ClassExtender Set User Placeholders' => array(
            'pagetitle' => 'ClassExtender Set User Placeholders',
            'alias' => 'class-extender-set-user-placeholders',
            'template' => 'default',
            'parent' => 'Examples',
            'richtext' => false,
            'published' => false,
        ),

        'ClassExtender User Search Form' => array(
            'pagetitle' => 'ClassExtender User Search Form',
            'alias' => 'class-extender-user-search-form',
            'template' => 'default',
            'parent' => 'Examples',
            'richtext' => false,
            'published' => false,
        ),


        'Extend modUser' => array(
            'pagetitle'   => 'Extend modUser',
            'alias'       => 'extend-moduser',
            'template'    => 'default',
            'parent'      => 'ClassExtender',
            'richtext'    => false,
            'published'   => false,
        ),
        'Extend modResource' => array(
            'pagetitle' => 'Extend modResource',
            'alias'     => 'extend-modresource',
            'template'  => 'default',
            'parent' => 'ClassExtender',
            'richtext'  => false,
            'published' => false,
        ),
        'Create Schema' => array(
            'pagetitle' => 'ClassExtender Create Schema',
            'alias' => 'classextender-create-schema',
            'template' => 'default',
            'parent' => 'ClassExtender',
            'richtext' => false,
            'published' => false,
        ),
    ),


    /* Array of languages for which you will have language files,
     *  and comma-separated list of topics
     *  ('.inc.php' will be added as a suffix). */
    'languages' => array(
        'en' => array(
            'default',
        ),
    ),
    /* ********************************************* */
    /* Define optional directories to create under assets.
     * Add your own as needed.
     * Set to true to create directory.
     * Set to hasAssets = false to skip.
     * Empty js and/or css files will be created.
     */
    'hasAssets' => true,

    'assetsDirs' => array(
        'css' => true,
    ),
    /* minify any JS files */
    'minifyJS' => false,
    /* Create a single JS file from all JS files */
    'createJSMinAll' => false,
    /* if this is false, regular jsmin will be used.
       JSMinPlus is slower but more reliable */
    'useJSMinPlus' => false,

    /* These will automatically go under assets/components/yourcomponent/js/
       Format: directory:filename
       (no trailing slash on directory)
       if 'createCmpFiles' is true, these will be ignored.
    */
    $jsFiles = array(

    ),


    /* ********************************************* */
    /* Define basic directories and files to be created in project*/

    'docs' => array(
        'readme.txt',
        'license.txt',
        'changelog.txt',
        'tutorial.html'
    ),

    /* (optional) Description file for GitHub project home page */
    'readme.md' => true,
    /* assume every package has a core directory */
    'hasCore' => true,

    /* ********************************************* */
    /* (optional) Array of extra script resolver(s) to be run
     * during install. Note that resolvers to connect plugins to events,
     * property sets to elements, resources to templates, and TVs to
     * templates will be created automatically -- *don't* list those here!
     *
     * 'default' creates a default resolver named after the package.
     * (other resolvers may be created above for TVs and plugins).
     * Suffix 'resolver.php' will be added automatically */
    'resolvers' => array(
        'default',
    ),

    /* (optional) Validators can abort the install after checking
     * conditions. Array of validator names (no
     * prefix of suffix) or '' 'default' creates a default resolver
     *  named after the package suffix 'validator.php' will be added */

    'validators' => array(
        'default',
    ),

    /* (optional) install.options is needed if you will interact
     * with user during the install.
     * See the user.input.php file for more information.
     * Set this to 'install.options' or ''
     * The file will be created as _build/install.options/user.input.php
     * Don't change the filename or directory name. */
    'install.options' => '',


    /* Suffixes to use for resource and element code files (not implemented)  */
    'suffixes' => array(
        'modPlugin' => '.php',
        'modSnippet' => '.php',
        'modChunk' => '.html',
        'modTemplate' => '.html',
        'modResource' => '.html',
    ),


    /* ********************************************* */
    /* (optional) Only necessary if you will have class files.
     *
     * Array of class files to be created.
     *
     * Format is:
     *
     * 'ClassName' => 'directory:filename',
     *
     * or
     *
     *  'ClassName' => 'filename',
     *
     * ('.class.php' will be appended automatically)
     *
     *  Class file will be created as:
     * yourcomponent/core/components/yourcomponent/model/[directory/]{filename}.class.php
     *
     * Set to array() if there are no classes. */
    'classes' => array(
        'ClassExtender' => 'classextender:classextender',
    ),

    /* ************************************
     *  These values are for CMPs.
     *  Set any of these to an empty array if you don't need them.
     *  **********************************/

    /* If this is false, the rest of this section will be ignored */

    'createCmpFiles' => false,

    /* IMPORTANT: The array values in the rest of
       this section should be all lowercase */

    /* This is the main action file for your component.
       It will automatically go in core/component/yourcomponent/
    */

    'actionFile' => 'index.php',

    /* CSS file for CMP */

    'cssFile' => 'mgr.css',

    /* These will automatically go to core/components/yourcomponent/processors/
       format directory:filename
       '.class.php' will be appended to the filename

       Built-in processor classes include getlist, create, update, duplicate,
       import, and export. */

    'processors' => array(
        'mgr/snippet:getlist',
        'mgr/snippet:changecategory',
        'mgr/snippet:remove',

        'mgr/chunk:getlist',
        'mgr/chunk:changecategory',
        'mgr/chunk:remove',
    ),

    /* These will automatically go to core/components/yourcomponent/controllers[/directory]/filename
       Format: directory:filename */

    'controllers' => array(
        ':index.php',
        'mgr:header.php',
        'mgr:home.php',
    ),

    /* These will automatically go in assets/components/yourcomponent/ */

    'connectors' => array(
        'connector.php'

    ),
    /* These will automatically go to assets/components/yourcomponent/js[/directory]/filename
       Format: directory:filename */

    'cmpJsFiles' => array(
        ':classextender.js',
        'sections:home.js',
        'widgets:home.panel.js',
        'widgets:snippet.grid.js',
        'widgets:chunk.grid.js',
    ),


    /* *******************************************
     * These settings control exportObjects.php  *
     ******************************************* */
    /* ExportObjects will update existing files. If you set dryRun
       to '1', ExportObjects will report what it would have done
       without changing anything. Note: On some platforms,
       dryRun is *very* slow  */

    'dryRun' => '0',

    /* Array of elements to export. All elements set below will be handled.
     *
     * To export resources, be sure to list pagetitles and/or IDs of parents
     * of desired resources
    */
    'process' => array(
        'snippets',
        'chunks',
        'resources',
        'plugins',
        'systemSettings',
    ),
    /*  Array  of resources to process. You can specify specific resources
        or parent (container) resources, or both.

        They can be specified by pagetitle or ID, but you must use the same method
        for all settings and specify it here. Important: use IDs if you have
        duplicate pagetitles */
    'getResourcesById' => false,

    'exportResources' => array(
        'Extend modUser',
        'Extend modResource',
        'ClassExtender',
        'Create Schema',
        'Examples',
        'ClassExtender Register PostHook',
        'ClassExtender Update Profile',
        'ClassExtender GetExtUsers',
        'ClassExtender GetExtResources',
        'ClassExtender Set Resource Placeholders',
        'ClassExtender Set User Placeholders',
        'ClassExtender User Search Form',

    ),
    /* Array of resource parent IDs to get children of. */
    'parents' => array(),
    /* Also export the listed parent resources
      (set 'parents' to false to include just the children) */
    'includeParents' => false,


    /* ******************** LEXICON HELPER SETTINGS ***************** */
    /* These settings are used by LexiconHelper */
    'rewriteCodeFiles' => true,  /* remove ~~descriptions */
    'rewriteLexiconFiles' => false, /* automatically add missing strings to lexicon files */
    /* ******************************************* */

    /* Array of aliases used in code for the properties array.
     * Used by the checkproperties utility to check properties in code against
     * the properties in your properties transport files.
     * if you use something else, add it here (OK to remove ones you never use.
     * Search also checks with '$this->' prefix -- no need to add it here. */
    'scriptPropertiesAliases' => array(
        'props',
        'sp',
        'config',
        'scriptProperties'
    ),
);

return $components;